CREATE TABLE SPRING_AI_CHAT_MEMORY (
    id VARCHAR(255) DEFAULT RANDOM_UUID() NOT NULL,
    conversation_id VARCHAR(255) NOT NULL,
    type VARCHAR(10) NOT NULL,
    content CLOB NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SPRING_AI_CHAT_MEMORY PRIMARY KEY (id),
    CONSTRAINT TYPE_CHECK CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);

CREATE INDEX SPRING_AI_CHAT_MEMORY_CONV_TS_IDX
    ON SPRING_AI_CHAT_MEMORY(conversation_id, TIMESTAMP DESC);